"""
services/gac_meta.py — Définitions centralisées des équipes et flottes
"""

# Score de défense (1 à 10) :
# 10 = Extrêmement défensif (Rey, Jabba, Grievous, Iden)
# 1 = Extrêmement offensif (Troopers, SLKR)
GAC_TEAMS = {
    # --- GALACTIC LEGENDS ---
    "JABBATHEHUTT": {"members": ["JABBATHEHUTT", "BOBAFETTSCION", "KRRSANTAN", "GAMORREANGUARD", "UNDERCOVERLANDO"], "defense": 10},
    "JEDIMASTERKENOBI": {"members": ["JEDIMASTERKENOBI", "PADMEAMIDALA", "GENERALSKYWALKER", "COMMANDERAHSOKA", "SHAAKTI"], "defense": 9},
    "LORDVADER": {"members": ["LORDVADER", "MARAJADE", "VADER", "ROYALGUARD", "DARTHNIHILUS"], "defense": 9},
    "SUPREMELEADERKYLOREN": {"members": ["SUPREMELEADERKYLOREN", "KYLORENUNMASKED", "GENERALHUX", "FIRSTORDERTIEPILOT", "FIRSTORDERSPECIALFORCESPILOT"], "defense": 5},
    "SITHPALPATINE": {"members": ["SITHPALPATINE", "VADER", "MARAJADE", "DARTHNIHILUS", "ROYALGUARD"], "defense": 3},
    
    # --- META & SECONDARY TEAMS ---
    "GRIEVOUS": {"members": ["GRIEVOUS", "B1BATTLEDROIDV2", "B2SUPERBATTLEDROID", "MAGNAGUARD", "DROIDEKA"], "defense": 10},
    "IDENVERSIOEMPIRE": {"members": ["IDENVERSIOEMPIRE", "DEATHTROOPER", "MAGMATROOPER", "SNOWTROOPER", "SHORETROOPER"], "defense": 10},
    "GEONOSIANBROODALPHA": {"members": ["GEONOSIANBROODALPHA", "GEONOSIANSPY", "GEONOSIANSOLDIER", "POGGLETHELESSER", "SUNFAC"], "defense": 9},
    "BOSSK": {"members": ["BOSSK", "BOBAFETT", "JANGOFETT", "GREEFKARGA", "MANDALORIAN"], "defense": 8},
    "MOTHERTALZIN": {"members": ["MOTHERTALZIN", "ASAJVENTRESS", "NIGHTSISTERZOMBIE", "OLDAKA", "MERRIN"], "defense": 8},
    "PADMEAMIDALA": {"members": ["PADMEAMIDALA", "JEDIKNIGHTANAKIN", "AHSOKATANO", "GENERALKENOBI", "C3POLEGENDARY"], "defense": 8},
    "MONMOTHMA": {"members": ["MONMOTHMA", "PETHESELVA", "CARADUNE", "KYLEKATARN", "HOTHREBELSCOUT"], "defense": 8},
    "DARTHREVAN": {"members": ["DARTHREVAN", "DARTHMALAK", "BASTILASHANDARK", "HK47", "SITHMARAUDER"], "defense": 7},
    "REYJEDITRAINING": {"members": ["REYJEDITRAINING", "BB8", "R2D2_LEGENDARY", "FINN", "RESISTANCETROOPER"], "defense": 7},
    "KYLORENUNMASKED": {"members": ["KYLORENUNMASKED", "KYLOREN", "SITHTROOPER", "FIRSTORDEREXECUTIONER", "FIRSTORDEROFFICERMALE"], "defense": 7},
    "JEDIKNIGHTREVAN": {"members": ["JEDIKNIGHTREVAN", "BASTILASHAN", "JOLEEBINDO", "GRANDMASTERYODA", "GENERALKENOBI"], "defense": 6},
    "CHIEFCHIRPA": {"members": ["CHIEFCHIRPA", "WICKET", "LOGRAY", "PAPLOO", "EWOKELDER"], "defense": 6},
    "QUIGONJINN": {"members": ["QUIGONJINN", "JEDIKNIGHTANAKIN", "KAM", "MACEWINDU", "AAYLASECURA"], "defense": 4},
    "SHAAKTI": {"members": ["SHAAKTI", "REX", "ECHO", "FIVES", "ARCTROOPER501ST"], "defense": 4},
    "HUNTER": {"members": ["HUNTER", "ECHO", "TECH", "WRECKER", "OMEGA"], "defense": 4},
    "COMMANDERLUKESKYWALKER": {"members": ["COMMANDERLUKESKYWALKER", "HANSOLO", "CHEWBACCALEGENDARY", "C3POCHEWBACCA", "C3POLEGENDARY"], "defense": 3},
    "GENERALVEERS": {"members": ["GENERALVEERS", "ADMIRALPIETT", "COLONELSTARCK", "RANGETROOPER", "DARKTROOPER"], "defense": 1},
}

# Flottes
GAC_FLEETS = {
    "CAPITALLEVIATHAN": {"members": ["CAPITALLEVIATHAN", "SITHFIGHTER", "SITHBOMBER", "FURYCLASSINTERCEPTOR", "MKVIINTERCEPTOR", "EBONHAWK", "SITHASSASSIN"], "defense": 10},
    "CAPITALEXECUTOR": {"members": ["CAPITALEXECUTOR", "HOUNDSTOOTH", "RAZORCREST", "XANADUBLOOD", "IG2000", "SLAVE1", "EBONHAWK", "TIEFIGHTER"], "defense": 10},
    "CAPITALPROFUNDITY": {"members": ["CAPITALPROFUNDITY", "MILLENNIUMFALCON", "OUTRIDER", "YWINGREBEL", "GHOST", "PHANTOM2", "CASSIANSUWING", "BISTANSUEING"], "defense": 8},
    "CAPITALNEGOTIATOR": {"members": ["CAPITALNEGOTIATOR", "JEDISTARFIGHTERANAKIN", "UMBARANSTARFIGHTER", "JEDISTARFIGHTERAHSOKATANO", "BTLB_YWING", "JEDISTARFIGHTERPLOKOON", "ARC170CLONESERGEANT", "ARC170REX"], "defense": 8},
    "CAPITALMALEVOLENCE": {"members": ["CAPITALMALEVOLENCE", "VULTUREDROID", "HYENABOMBER", "GEONOSIANSTARFIGHTERSUNFAC", "GEONOSIANSTARFIGHTERSPY", "GEONOSIANSTARFIGHTER", "IG2000"], "defense": 7},
    "CAPITALCHIMAERA": {"members": ["CAPITALCHIMAERA", "TIEADVANCED", "TIEBOMBER", "TIEDEFENDER", "TIEINTERCEPTOR", "TIEFIGHTER", "GAUNTLETSTARFIGHTER", "EMPERORSSHUTTLE"], "defense": 6},
    "CAPITALSTARDESTROYER": {"members": ["CAPITALSTARDESTROYER", "TIEADVANCED", "TIEBOMBER", "TIEDEFENDER", "TIEINTERCEPTOR", "TIEFIGHTER", "GAUNTLETSTARFIGHTER", "EMPERORSSHUTTLE"], "defense": 5},
    "CAPITALFINALIZER": {"members": ["CAPITALFINALIZER", "KYLORENSCOMMANDSHUTTLE", "TIESILENCER", "FIRSTORDERSPECIALFORCESTIEFIGHTER", "FIRSTORDERTIEFIGHTER", "HOUNDSTOOTH"], "defense": 3},
    "CAPITALRADDUS": {"members": ["CAPITALRADDUS", "REYSMILLENNIUMFALCON", "RESISTANCEYWING", "POE_XWING", "RESISTANCE_XWING", "EBOE_XWING"], "defense": 5},
}
